server:
  port: 8070
spring:
  application:
    name: sidecar
  cloud:
    consul:
      # 将consul 与 springboot的健康检查整合在一起，默认就是 /actuator/health
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}
        health-check-path: /actuator/health
        prefer-ip-address: true
        # 设置 Spring Cloud 的元数据
        tags: JIFANG=NJ
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          # 让springcloud gateway 自动从服务发现组件找到其他微服务，并反向代理
          enabled: true

# spring boot actuator 相关依赖
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
sidecar:
  # 指定异构微服务的ip
  ip: 127.0.0.1
  # 指定异构微服务的端口
  port: 8060
  # 指定异构微服务的健康检查端点
  health-check-url: http://localhost:8060/health.json
