server:
  port: 8040
spring:
  application:
    name: ms-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.hostname}
        tags: JIFANG=NJ
    gateway:
      discovery:
        locator:
          # 让gateway从服务发现找到微服务，并反向代理
          enabled: true
      routes:
        - id: host_route
          # lb://表示从服务发现组件上找到指定微服务
          uri: lb://ms-user
          predicates:
            # 当且仅当名为Host的Header符合**.somehost.org或**.anotherhost.org时，才会转发用户微服务
            # 如Host满足条件，则访问http://localhost:8040/** -> ms-user/**
            # eg. 访问http://localhost:8040/users/1 -> ms-user/users/1
            - Host=**.somehost.org,**.anotherhost.org
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace