server:
  port: 8040
spring:
  application:
    name: ms-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.hostname}
        tags: JIFANG=NJ
    gateway:
      discovery:
        locator:
          # 让gateway从服务发现找到微服务，并反向代理
          enabled: true
      routes:
        - id: remoteaddr_route
          # lb://表示从服务发现组件上找到指定微服务
          uri: lb://ms-user
          predicates:
            # 当且仅当请求IP是192.168.1.1/24网段，例如192.168.1.10，才会转发到用户微服务
            # eg. 访问http://localhost:8040/users/1 -> ms-user的/users/1
            - RemoteAddr=192.168.1.1/24
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace